//PORDUCT DETAILS
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAIL_REQUEST'; 
export const PRODUCT_DETAILS_SECCESS = 'PRODUCT_DETAIL_SECCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAIL_SECCESS';